# Generated by Django 4.2 on 2024-12-05 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventureApp', '0004_alter_booking_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('designation', models.CharField(choices=[('LEAD', 'Lead Guide'), ('ASSISTANT', 'Assistant Guide'), ('FREELANCE', 'Freelance Guide'), ('LOCAL', 'Local Guide')], default='LOCAL', max_length=20)),
                ('experience_years', models.IntegerField(help_text='Years of experience (must be 0 or more)', validators=[django.core.validators.MinValueValidator(0)])),
                ('education', models.CharField(blank=True, max_length=300, null=True)),
                ('languages_spoken', models.TextField(blank=True, help_text='Comma-separated list of languages', null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='tour_guides/profile_pictures/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tours', models.ManyToManyField(blank=True, related_name='guides', to='adventureApp.tour')),
            ],
            options={
                'verbose_name': 'Tour Guide',
                'verbose_name_plural': 'Tour Guides',
                'ordering': ['name'],
            },
        ),
    ]
