# Generated by Django 4.2 on 2024-12-07 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventureApp', '0006_destination_alter_tour_featured_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='max_group_size',
            field=models.PositiveIntegerField(help_text='Maximum number of participants for this tour', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
